### ISSUE TITLE
本地运行问题

### ISSUE THREAD

**Issue by jessjava** [nicejade/nicelinks-koa2-api#2]
1. src/helper/nodemailer.js 文件中4、5行引入的./../config/secret 没有secret文件
2. 注册功能无法使用
3./api/getSysConf 404,这个接口做什么用的？

**Comment by nicejade** [comment]
其实，这个库已经未在维护了；对于 secret 文件，可以创建一个 `secret .js`，内容格式如下即可。

```js
module.exports = {
  email_163: {
    account: 'your-163-account',
    password: 'your-163-pwd',
  },
  email_qq: {
    account: 'your-qq-account',
    password: 'your-qq-pwd',
  }
}
```

`/api/getSysConf ` 这个接口使用来拉取后台系统配置的；可以参见 [nicelinks.site 请求](https://nicelinks.site/explore/all)。

**Comment by jessjava** [comment]
感谢，想咨询一下如果在本地运行 nicelinks-vue-client, 方便更好的学习。后端应该怎么部署？感谢

**Comment by nicejade** [comment]
@jessjava 可以运行此项目 `npm run start`，当然前提是需要手动安装并打开 MongoDb 和 Redis。
